server:
  port: 9999
  contextPath: /

spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/entity?characterEncoding=utf8&useUnicode=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

logging.level.org.hibernate.SQL: debug